### ISSUE TITLE
Repeatedly saving a pre-existing torrent

### ISSUE THREAD

**Issue by LXGaming** [cross-seed/cross-seed#308]
I've noticed that cross-seed is constantly finding a match even though the torrent in question already exists in rTorrent and is present in the watch folder, cross-seed is re-writing the torrent file to the watch folder and triggering the webhook notification every time this happens.

I would expect the behavior of cross-seed to be that this torrent is ignore or detected as already existing.

Note: `[redacted]` in the log below is a single torrent.
```
info: [server] Received search request: { infoHash: '[redacted]' }
info: Found [redacted] on [redacted] - saved
info: [server] Found 1 torrents for { infoHash: '[redacted]' }
info: [scheduler] starting job: rss
info: Found [redacted] on [redacted] - saved
info: [rss] Scan complete
info: [scheduler] starting job: rss
info: Found [redacted] on [redacted] - saved
info: [rss] Scan complete
info: [scheduler] starting job: rss
info: Found [redacted] on [redacted] - saved
info: [rss] Scan complete
info: [scheduler] starting job: rss
info: Found [redacted] on [redacted] - saved
info: [rss] Scan complete
info: [server] Received search request: { infoHash: '[redacted]' }
info: Found [redacted] on [redacted] - saved
info: [server] Found 1 torrents for { infoHash: '[redacted]' }
```

**Comment by mmgoodnow** [comment]
this is currently WAD but you bring up a good point that we could reuse the `- exists` logic for saving in addition to injecting.

Is the overwriting causing a problem for you, or just the notifications?

**Comment by bakerboy448** [comment]
seeing this with qbit too.  no known issues other than notification spam

**Comment by LXGaming** [comment]
The overwriting isn't causing any issues for rTorrent although it would be nice if cross-seed didn't make unnecessary writes, The notification spam is the main issue.

**Comment by gappie** [comment]
Would be great to have this fixed. I am using the save method and rely on notifications to enable cross seeds once the original torrent is done downloading. Being repeatedly notified is a problem.

**Comment by Hydrometry** [comment]
This is an issue for me as well, when just doing `cross-seed search`, with `--action save` and using another tool to inject to qBittorrent. The torznab response includes the infohash with many trackers, right? Shouldn't the incoming torrent's infohash be checked against all the infohashes in `--torrentDir`? Right now it's wasting grabs on those duplicates, which increases the chance of getting temp banned from downloading torrents.

**Comment by Undrog** [comment]
Just to pile on... this causes similar pain for me. I have cross-seed saving to a directory where I have a script watching for new files. Every 10 minutes I get the same new file again.

My suggestion would be to cache the torrent download URL, so it does not try to download the same torrent again, this will minimize the requests to the tracker instead of needing to download/inspect the torrent file.

**Comment by Undrog** [comment]
Implementations appear to be inconsistent regarding whether infohash is returned, as you said "many trackers" include this perhaps. This could be a good way to reduce the requests, as long as we don't depend on the presence of infohash in the results.

I guess as a 2nd check, once the file is grabbed, it could check the torrentfile for infohash against the torrentDir before saving/injecting as well.

**Comment by mmgoodnow** [comment]
hey folks! I believe this is fixed in the `next` branch. It turns out that this was a regression, introduced in v4, but I had just completely forgotten what the original intended behavior was. 

> Shouldn't the incoming torrent's infohash be checked against all the infohashes in --torrentDir?

This was the original behavior

**Comment by NGDM** [comment]
I'm still encountering this issue with latest update:

Cross-seed logs:
```text
Configuration file already exists.
info: Validating your configuration...
info: Your configuration is valid!
info: [search] Found 629 torrents, 1 suitable to search for matches
info: [1/1] Searching for *redacted*
info: Found *redacted*.mkv on *redacted* - saved
info: [search] Found 1 cross seeds from 1 original torrents
```

Deluge logs:
```text
22:51:18 [INFO    ][deluge.core.torrent           :1622] Adding any new trackers to torrent (*redacted*) already in session...
22:51:18 [INFO    ][deluge.core.torrent           :1622] Adding trackers aborted: Torrent has private flag set.
22:51:18 [ERROR   ][deluge_autoadd.core           :1622] Cannot Autoadd torrent file: /data/downloads/incoming/[movie][*redacted*]*redacted*.torrent: Torrent already in session (*redacted*).
```

Is it possible this wasn't fixed for save action?

**Comment by mmgoodnow** [comment]
It will not stop outputting that file until it is found in the input dir

**Comment by NGDM** [comment]
@mmgoodnow Input dir is the "state" folder in Deluge config. It contains all active torrents, including the example I had above.

I also find it in the torrent_cache folder in cross-seed config, if that matters. 

I don't see this exact torrent mentioned in the verbose logging, yet it is added at the end of the search.
Is this a caching issue maybe? Should I try removing some db or cache files?
