### ISSUE TITLE
Need to sleep before posting to webhook from qbit

### ISSUE THREAD

**Issue by undaunt** [cross-seed/cross-seed#439]
I'm successfully running docker, daemon mode, and doing a bulk search of old torrents without issue. However, when I test downloaded 1 new movie using the specified script `curl -XPOST http://localhost:2468/api/webhook --data-urlencode "name=%N"` I get an error on execution that the file cannot be found.

However, I checked one of my trackers and I see that it is in fact there. I'm wondering what could be causing a specific torrent file to fail during on-demand execution to search when all is working in bulk search?

Thanks.

**Comment by undaunt** [comment]
I was reading through https://github.com/cross-seed/cross-seed/issues/383 so I switched my qB instances to refer back to infohash, similar to how I had the bash scripts set up for an older version of cross seed. They used to call the .sh file which contained:

```
#!/bin/bash

curl -XPOST cs-tv:2468/api/webhook \
  -H 'Content-Type: application/json' \
  --data '{"infoHash":"'"${1}"'"}'

exit 0
```

This still didn't work, but when I manually triggered my old script (noted above) with a ./cross-seed.sh infohashvalue, the search kicked off. The two log entries for the search look almost identical:

**qB post-download execution**
```
06/22/2023 10:43:53 PM
info: [server] Received search request: { infoHash: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx' }
06/22/2023 10:43:54 PM
error: could not find a torrent with the criteria { infoHash: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx' }
```

**versus .sh file execution**
```
06/22/2023 10:45:19 PM
info: [server] Received search request: { infoHash: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx' }
06/22/2023 10:45:19 PM
info: [torznab] Searching 3 indexers for nameofMovie
06/22/2023 10:45:25 PM
info: [server] Found 0 torrents for { infoHash: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx' }
```

What's also odd is I know this particular movie is on at least one other tracker in my Prowlarr config, and I can see it in Radarr results, same file size, but it's not being picked up.

I'm having no issues whatsoever with daemon mode for injection into qB or manual search.

**Comment by undaunt** [comment]
Did some more digging on the discord and referred to the posts in #365. I'm trying to simplify the exact issue by not using the old bash script at all and only testing with infoHash.

When a movie finished downloading, (and I verified my qB is still set to fastresume, not sqlite experimental), it failed, but I then manually executed: `docker exec -ti qb-movies bash -c 'curl -XPOST http://cs-mov:2468/api/webhook -v --data-urlencode "infoHash=cfde9808e2812771663741d31d57d59cb3af4be5"'` and it worked. Both instances below:

```
2023-06-24 03:07:38 ^[[32minfo^[[39m: [server] Received search request: { infoHash: 'cfde9808e2812771663741d31d57d59cb3af4be5' }
2023-06-24 03:07:39 ^[[31merror^[[39m: could not find a torrent with the criteria { infoHash: 'cfde9808e2812771663741d31d57d59cb3af4be5' }
2023-06-24 03:07:39 ^[[34mdebug^[[39m: could not find a torrent with the criteria { infoHash: 'cfde9808e2812771663741d31d57d59cb3af4be5' }
2023-06-24 03:08:55 ^[[36mverbose^[[39m: [server] POST /api/webhook
2023-06-24 03:08:55 ^[[32minfo^[[39m: [server] Received search request: { infoHash: 'cfde9808e2812771663741d31d57d59cb3af4be5' }
2023-06-24 03:08:56 ^[[32minfo^[[39m: [torznab] Searching 3 indexers for Disobedience 2017 BluRay 1080p DTS x264-VietHD.mkv
```

As far as I can tell there is no difference between line 1 and line 5, and I have both a fastresume file and torrent file from 8:09pm in my data folder. Perhaps the files are being created after the completion call in these newer versions of qB? The execution appeared to trigger at 8:07.

**Comment by undaunt** [comment]
I dug more into the timing issue. Right now, executing a bash script with just a 1 or 2 second sleep works, whereas no sleep throws the criteria error, and directly issuing the webhook post from qB 4.5.3 also throws the error. I'm not technical enough to discern why, but here is a working (for me at least) solution for those of us on a more recent qB release:

Execute on completion of download:
`/config/cross-seed.sh "%N"` or `/config/cross-seed.sh "%I"` depending on preference

Then the script would be either:

```
#!/bin/bash

sleep 2

curl -XPOST cs-mov:2468/api/webhook \
  -H 'Content-Type: application/json' \
  --data '{"infoHash":"'"${1}"'"}'

exit 0
```

or

```
#!/bin/bash

sleep 2

curl -XPOST cs-tv:2468/api/webhook \
  -H 'Content-Type: application/json' \
  --data '{"name":"'"${1}"'"}'

exit 0
```

Respectively, depending on people's preference for infohash versus name being sent. @mmgoodnow Is there a better/worse choice here? I'm running in safe mode, no data matching fwiw. Of course, rename your containers/use localhost as appropriate.

Thanks for any insight.

**Comment by mmgoodnow** [comment]
thanks for digging into this! I'm not sure why the timing would be an issue - definitely worth looking into on my end. It's possible it's a qbit problem though. 

As for name vs info hash, qbit users should probably use info hash but it only matters if you use the Subfolder content layout (this is when single-file torrents get put into a folder with the file extension stripped) because qbittorrent mutates the torrent files. All other clients I know of can use name just fine.

**Comment by adamflagg** [comment]
I'm seeing a similar issue now where sleep is also not resolving the prior workaround. @karserasl What version of QB are you on?

**Comment by undaunt** [comment]
I'm seeing a similar issue now where sleep is also not resolving the prior workaround. @karserasl What version of QB are you on?

**Comment by coolguymatt** [comment]
I am on qBittorrent 4.5.5 and have the same issue.

**Comment by undaunt** [comment]
I bumped the delay up to 5s and it's been working for me again.

**Comment by zakkarry** [comment]
This has been resolved with sleep in a bash script, which seems to be a pretty minimal, and easily overcome, issue.

If this can be replicated consistently please post and reopen this with setup/steps with surrounding cross-seed verbose logs and if anything is in qBit's those too. I can't replicate this, and arbitrarily adding a delay rather than fixing the issue is not a viable solution. 

Otherwise, I'm not sure how to address this.

**Comment by mmgoodnow** [comment]
A worthwhile debugging test to do here, to identify if the problem is on cross-seed's end or qbittorrent's end, is to look for a torrent named `%I.torrent` in BT_backup inside the bash script. You could even do that with some sleeping in a loop to see how long it usually takes to show up

**Comment by mgpsp** [comment]
This is still happening on qBittorrent 5.1.0 (Debian 13), cross-seed 6.13.6. Has anyone found a solution at all? Even sleeping 30 seconds before posting does not work most of the time. I have checked and the .torrent file is in the BT_Backup folder at the time we are posting to the endpoint, so it does not make sense why it can't find the torrent.
